"""Auto-generated FastMCP server: Google Flights Search
Generated by NoUI v1
"""
from __future__ import annotations

import json

from mcp.server.fastmcp import FastMCP

from operations import create_data_batchexecute as _op_search_airports_cities
from operations import create_travel_frontend_flights_flightsfrontendservice_getcalendarpicker as _op_get_flight_prices_calendar
from operations import create_travel_frontend_flights_flightsfrontendservice_getshoppingresults as _op_search_flights


mcp = FastMCP("Google Flights Search")


def _fmt_time(hm: list | None) -> str | None:
    if not hm:
        return None
    h = hm[0]
    m = hm[1] if len(hm) > 1 else 0
    return f"{h:02d}:{m:02d}"


def _fmt_datetime(date: list | None, hm: list | None) -> str | None:
    if not date or not hm:
        return None
    return f"{date[0]}-{date[1]:02d}-{date[2]:02d}T{_fmt_time(hm)}"


def _parse_segment(seg: list) -> dict:
    flight_info = seg[22] if len(seg) > 22 else None
    return {
        "flight": f"{flight_info[0]}{flight_info[1]}" if flight_info else None,
        "from": seg[3],
        "to": seg[6],
        "dep": _fmt_datetime(seg[20] if len(seg) > 20 else None, seg[8]),
        "arr": _fmt_datetime(seg[21] if len(seg) > 21 else None, seg[10]),
        "duration_min": seg[11],
        "aircraft": seg[17] if len(seg) > 17 else None,
    }


def _parse_flight_item(flight: list) -> dict:
    finfo = flight[0]
    price_raw = flight[1]
    segments = finfo[2] or []
    airline_names = finfo[1] or []
    price = price_raw[0][1] if price_raw and price_raw[0] else None
    legs = []
    for seg in segments:
        try:
            legs.append(_parse_segment(seg))
        except Exception:
            pass
    return {
        "airline": finfo[0],
        "airline_name": airline_names[0] if airline_names else finfo[0],
        "price_BRL": price,
        "stops": max(0, len(segments) - 1),
        "legs": legs,
    }


def _parse_flights_response(raw: dict) -> dict:
    """Parse raw Google Flights wire-format response into compact structured data."""
    try:
        text = raw.get("text", "")
        lines = text.split("\n", 3)
        if len(lines) < 4:
            return {"error": "Unexpected response format", "raw_preview": text[:200]}

        decoder = json.JSONDecoder()
        obj, _ = decoder.raw_decode(lines[3].lstrip())
        flights_data = json.loads(obj[0][2])

        top_picks: list[dict] = []
        all_results: list[dict] = []

        if flights_data[2] and flights_data[2][0]:
            for f in flights_data[2][0]:
                try:
                    top_picks.append(_parse_flight_item(f))
                except Exception:
                    pass

        if flights_data[3] and flights_data[3][0]:
            for f in flights_data[3][0]:
                try:
                    all_results.append(_parse_flight_item(f))
                except Exception:
                    pass

        return {"top_picks": top_picks, "all_results": all_results, "total": len(all_results)}

    except Exception as e:
        return {"error": str(e), "raw_preview": str(raw)[:500]}


@mcp.tool()
async def search_airports_cities(
    query: str,
    csrf_token: str = "",
) -> dict:
    """Search for airports and cities by name. Returns matching locations with their Google entity IDs (e.g. '/m/022pfm' for São Paulo) needed by the flight search tools."""
    return await _op_search_airports_cities.execute(query=query, csrf_token=csrf_token)


@mcp.tool()
async def get_flight_prices_calendar(
    origin_entity_id: str,
    destination_entity_id: str,
    calendar_start: str,
    calendar_end: str,
    csrf_token: str = "",
) -> dict:
    """Return a price calendar for a round-trip route across a date range. Use origin/destination entity IDs from search_airports_cities. Useful for finding the cheapest dates before calling search_flights."""
    return await _op_get_flight_prices_calendar.execute(
        origin_entity_id=origin_entity_id,
        destination_entity_id=destination_entity_id,
        calendar_start=calendar_start,
        calendar_end=calendar_end,
        csrf_token=csrf_token,
    )


@mcp.tool()
async def search_flights(
    origin_entity_id: str,
    destination_entity_id: str,
    departure_date: str,
    return_date: str = "",
    adults: int = 1,
    csrf_token: str = "",
) -> dict:
    """Search for available flights. Returns options with prices, airlines, and schedules for the given route and dates. Use origin/destination entity IDs from search_airports_cities. Leave return_date empty for one-way."""
    raw = await _op_search_flights.execute(
        origin_entity_id=origin_entity_id,
        destination_entity_id=destination_entity_id,
        departure_date=departure_date,
        return_date=return_date,
        adults=adults,
        csrf_token=csrf_token,
    )
    return _parse_flights_response(raw)


if __name__ == "__main__":
    mcp.run()
