// Minimal ESLint 9 flat config for the Chrome extension.
// Scope: catch undefined identifiers in extension JS. Style is not enforced.

export default [
  {
    ignores: ["lib/**", "**/vendor/**"],
  },
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        chrome: "readonly",
        window: "readonly",
        document: "readonly",
        console: "readonly",
        fetch: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        FormData: "readonly",
        Blob: "readonly",
        File: "readonly",
        FileReader: "readonly",
        TextDecoder: "readonly",
        TextEncoder: "readonly",
        AbortController: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        CustomEvent: "readonly",
        Event: "readonly",
        HTMLElement: "readonly",
        Image: "readonly",
        atob: "readonly",
        btoa: "readonly",
        structuredClone: "readonly",
        crypto: "readonly",
        self: "readonly",
        globalThis: "readonly",
        location: "readonly",
        navigator: "readonly",
        performance: "readonly",
        alert: "readonly",
        createImageBitmap: "readonly",
        OffscreenCanvas: "readonly",
        CSS: "readonly",
        HTMLTextAreaElement: "readonly",
        HTMLInputElement: "readonly",
        MutationObserver: "readonly",
        getComputedStyle: "readonly",
        KeyboardEvent: "readonly",
        SpeechSynthesisUtterance: "readonly",
        speechSynthesis: "readonly",
        SpeechRecognition: "readonly",
        webkitSpeechRecognition: "readonly",
        MediaRecorder: "readonly",
        AudioContext: "readonly",
        webkitAudioContext: "readonly",
      },
    },
    rules: {
      "no-undef": "error",
      "no-unused-vars": "off",
    },
  },
];
