"""Generate the FastMCP server.py and orchestrate the full MCP compilation pipeline.

Pure functions for code generation; compile_workflow handles file I/O.
"""

from __future__ import annotations

import json
import os
import re
from pathlib import Path

from compiler.mcp.har_to_tools import har_entries_to_tool_defs
from compiler.mcp.tool_generator import generate_operation_module
from compiler.mcp.manifest_generator import generate_manifest
from compiler.mcp import auth_adapter as _auth_adapter_mod

from backend.shared.har_analyzer import filter_har_entries, annotate_har_entries
from backend.shared.auth_detector import detect_auth_from_har


# ── Server source generation ─────────────────────────────────────────────────

def generate_server(
    tool_defs: list[dict],
    tabby_profile_id: str,
    server_name: str,
) -> str:
    """Generate the FastMCP server.py source code as a string.

    Produces a runnable FastMCP server that imports each operation module and
    registers it as an MCP tool.
    """
    if not tool_defs:
        return _empty_server(server_name)

    lines: list[str] = [
        f'"""Auto-generated FastMCP server: {server_name}',
        "Generated by NoUI v1",
        '"""',
        "from __future__ import annotations",
        "",
        "from mcp.server.fastmcp import FastMCP",
        "",
    ]

    # Import each operation module with _op_ prefix to avoid shadowing tool function names
    for td in tool_defs:
        lines.append(f"from operations import {td['name']} as _op_{td['name']}")
    lines.append("")
    lines.append("")
    lines.append(f'mcp = FastMCP("{server_name}")')
    lines.append("")
    lines.append("")

    # Register each tool
    for td in tool_defs:
        name = td["name"]
        description = td.get("description", f"Execute {name}")
        params = td.get("params", [])

        # Build signature
        sig_parts = _build_tool_signature(params)
        if sig_parts:
            if len(sig_parts) == 1:
                sig_str = sig_parts[0]
            else:
                inner = ",\n    ".join(sig_parts)
                sig_str = f"\n    {inner},\n"
        else:
            sig_str = ""

        # Build call args
        call_args = ", ".join(f"{p['name']}={p['name']}" for p in params)

        lines.append("@mcp.tool()")
        lines.append(f"async def {name}({sig_str}) -> dict:")
        lines.append(f'    """{description}"""')
        if call_args:
            lines.append(f"    return await _op_{name}.execute({call_args})")
        else:
            lines.append(f"    return await _op_{name}.execute()")
        lines.append("")
        lines.append("")

    lines.append('if __name__ == "__main__":')
    lines.append("    mcp.run()")
    lines.append("")

    return "\n".join(lines)


def _empty_server(server_name: str) -> str:
    return (
        f'"""Auto-generated FastMCP server: {server_name}\n'
        "Generated by NoUI v1\n"
        '"""\n'
        "from __future__ import annotations\n\n"
        "from mcp.server.fastmcp import FastMCP\n\n"
        f'mcp = FastMCP("{server_name}")\n\n'
        'if __name__ == "__main__":\n'
        "    mcp.run()\n"
    )


def _build_tool_signature(params: list[dict]) -> list[str]:
    """Build function signature params for the server.py tool wrapper."""
    from compiler.mcp.tool_generator import _build_signature_params
    return _build_signature_params(params)


# ── App name derivation ──────────────────────────────────────────────────────

def _app_name_from_slug(app_slug: str) -> str:
    """Convert 'hubspot' → 'HubSpot' (best effort title-case)."""
    return " ".join(word.capitalize() for word in app_slug.replace("-", " ").split())


# ── Full compilation pipeline ────────────────────────────────────────────────

def compile_workflow(
    session_id: str,
    session_name: str,
    app_slug: str,
    tabby_profile_id: str,
    har: dict,
    click_events: list[dict],
    url_events: list[dict],
    output_dir: str,
) -> dict:
    """Full compilation pipeline.

    Steps:
    1. Filter HAR entries
    2. Annotate with click context
    3. Detect auth signals
    4. Convert to tool defs
    5. Generate operation modules
    6. Generate server.py
    7. Generate manifest.json
    8. Write all files to output_dir
    9. Return the manifest dict

    Args:
        session_id: UUID of the WorkflowSession.
        session_name: Human-readable name (used as server name and for tool descriptions).
        app_slug: URL-safe lowercase slug (e.g. "hubspot").
        tabby_profile_id: Tabby credential profile ID to embed in generated code.
        har: Parsed HAR dict (standard HAR 1.2 format).
        click_events: List of ClickEvent dicts (serialised ORM objects).
        url_events: List of UrlEvent dicts (serialised ORM objects).
        output_dir: Absolute path to write generated files into.

    Returns:
        The manifest dict.
    """
    # 1. Filter HAR entries
    filtered = filter_har_entries(har)

    # 2. Annotate with click context
    annotated = annotate_har_entries(filtered, click_events=click_events)

    # 3. Detect auth signals
    auth_info = detect_auth_from_har(har)

    # 4. Convert to tool defs
    tool_defs = har_entries_to_tool_defs(annotated, auth_info, session_name=session_name)

    # 5. Generate operation module sources
    op_sources: dict[str, str] = {}
    for td in tool_defs:
        source = generate_operation_module(td, tabby_profile_id)
        op_sources[td["name"]] = source

    # 6. Generate server.py
    server_source = generate_server(tool_defs, tabby_profile_id, session_name)

    # 7. Determine server_id and output paths
    server_id = f"{app_slug}-{session_id[:8]}"
    app_name = _app_name_from_slug(app_slug)

    # Collect file list for manifest
    output_files: list[str] = ["server.py", "tools.json", "noui_runtime/auth.py"]
    for name in op_sources:
        output_files.append(f"operations/{name}.py")

    # 8. Write files
    out_path = Path(output_dir)
    out_path.mkdir(parents=True, exist_ok=True)

    # server.py
    (out_path / "server.py").write_text(server_source, encoding="utf-8")

    # tools.json
    (out_path / "tools.json").write_text(
        json.dumps(tool_defs, indent=2, default=str), encoding="utf-8"
    )

    # operations/
    ops_dir = out_path / "operations"
    ops_dir.mkdir(exist_ok=True)
    (ops_dir / "__init__.py").write_text("", encoding="utf-8")
    for name, source in op_sources.items():
        (ops_dir / f"{name}.py").write_text(source, encoding="utf-8")

    # noui_runtime/auth.py
    from backend.config import settings as _settings
    runtime_dir = out_path / "noui_runtime"
    runtime_dir.mkdir(exist_ok=True)
    (runtime_dir / "__init__.py").write_text("", encoding="utf-8")
    auth_source = _auth_adapter_mod.generate_auth_adapter(
        tabby_profile_id, _settings.tabby_api_host
    )
    (runtime_dir / "auth.py").write_text(auth_source, encoding="utf-8")

    # 9. Generate and write manifest
    manifest = generate_manifest(
        server_id=server_id,
        app_name=app_name,
        app_slug=app_slug,
        workflow_session_id=session_id,
        workflow_name=session_name,
        tabby_profile_id=tabby_profile_id,
        tool_defs=tool_defs,
        output_files=output_files,
    )
    (out_path / "manifest.json").write_text(
        json.dumps(manifest, indent=2), encoding="utf-8"
    )

    return manifest
