"""Generate the FastMCP server.py and orchestrate the full MCP compilation pipeline.

Pure functions for code generation; compile_workflow handles file I/O.
"""

from __future__ import annotations

import json
import os
import re
from pathlib import Path

from compiler.mcp.har_to_tools import har_entries_to_tool_defs
from compiler.mcp.tool_generator import generate_operation_module
from compiler.mcp.manifest_generator import generate_manifest
from compiler.mcp.auth_plan import generate_auth_plan
from compiler.mcp import auth_adapter as _auth_adapter_mod

from backend.shared.har_analyzer import filter_har_entries, annotate_har_entries
from backend.shared.auth_detector import detect_auth_from_har


# ── Server source generation ─────────────────────────────────────────────────

def generate_server(
    tool_defs: list[dict],
    tabby_profile_id: str,
    server_name: str,
) -> str:
    """Generate the FastMCP server.py source code as a string."""
    if not tool_defs:
        return _empty_server(server_name)

    lines: list[str] = [
        f'"""Auto-generated FastMCP server: {server_name}',
        "Generated by NoUI v2",
        '"""',
        "from __future__ import annotations",
        "",
        "from mcp.server.fastmcp import FastMCP",
        "",
    ]

    for td in tool_defs:
        lines.append(f"from operations import {td['name']} as _op_{td['name']}")
    lines.append("")
    lines.append("")
    lines.append(f'mcp = FastMCP("{server_name}")')
    lines.append("")
    lines.append("")

    for td in tool_defs:
        name = td["name"]
        description = td.get("description", f"Execute {name}")
        params = td.get("params", [])

        sig_parts = _build_tool_signature(params)
        if sig_parts:
            if len(sig_parts) == 1:
                sig_str = sig_parts[0]
            else:
                inner = ",\n    ".join(sig_parts)
                sig_str = f"\n    {inner},\n"
        else:
            sig_str = ""

        call_args = ", ".join(f"{p['name']}={p['name']}" for p in params)

        lines.append("@mcp.tool()")
        lines.append(f"async def {name}({sig_str}) -> dict:")
        lines.append(f'    """{description}"""')
        if call_args:
            lines.append(f"    return await _op_{name}.execute({call_args})")
        else:
            lines.append(f"    return await _op_{name}.execute()")
        lines.append("")
        lines.append("")

    lines.append('if __name__ == "__main__":')
    lines.append("    mcp.run()")
    lines.append("")

    return "\n".join(lines)


def _empty_server(server_name: str) -> str:
    return (
        f'"""Auto-generated FastMCP server: {server_name}\n'
        "Generated by NoUI v2\n"
        '"""\n'
        "from __future__ import annotations\n\n"
        "from mcp.server.fastmcp import FastMCP\n\n"
        f'mcp = FastMCP("{server_name}")\n\n'
        'if __name__ == "__main__":\n'
        "    mcp.run()\n"
    )


def _build_tool_signature(params: list[dict]) -> list[str]:
    from compiler.mcp.tool_generator import _build_signature_params
    return _build_signature_params(params)


# ── App name derivation ──────────────────────────────────────────────────────

def _app_name_from_slug(app_slug: str) -> str:
    return " ".join(word.capitalize() for word in app_slug.replace("-", " ").split())


# ── Full compilation pipeline ────────────────────────────────────────────────

def compile_workflow(
    session_id: str,
    session_name: str,
    app_slug: str,
    tabby_profile_id: str,
    har: dict,
    click_events: list[dict],
    url_events: list[dict],
    output_dir: str,
    profile_slug: str = "",
    profile_db_id: str = "",
) -> dict:
    """Full compilation pipeline.

    Steps:
    1.  Filter HAR entries
    2.  Annotate with click context
    3.  Detect auth signals
    4.  Generate AuthPlan from HAR signals + profile metadata
    5.  Convert to tool defs
    6.  Generate operation modules (auth_plan drives header merging + strategy)
    7.  Generate server.py
    8.  Write all files to output_dir
    9.  Write auth_plan.json
    10. Generate and write manifest.json
    11. Return the manifest dict

    Args:
        session_id: UUID of the WorkflowSession.
        session_name: Human-readable name.
        app_slug: URL-safe lowercase slug (e.g. "hubspot").
        tabby_profile_id: Legacy profile identifier — may be a UUID or slug.
            Deprecated in favour of profile_slug; kept for backward compatibility.
        profile_slug: Tabby profile slug for runtime credential requests.
            Takes precedence over tabby_profile_id when both are provided.
        profile_db_id: Tabby profile DB UUID for admin operations only.
            Never used for runtime credential requests.
        har, click_events, url_events: Raw recording data.
        output_dir: Absolute path to write generated files into.

    Returns:
        The manifest dict.
    """
    # Resolve effective profile slug: explicit slug > legacy tabby_profile_id
    effective_slug = profile_slug or tabby_profile_id or ""

    # 1. Filter HAR entries
    filtered = filter_har_entries(har)

    # 2. Annotate with click context
    annotated = annotate_har_entries(filtered, click_events=click_events)

    # 3. Detect auth signals
    auth_info = detect_auth_from_har(har)

    # 4. Generate AuthPlan when auth signals are present
    auth_plan: dict = {}
    if auth_info.get("has_auth_headers") or auth_info.get("has_cookies"):
        auth_plan = generate_auth_plan(
            har=har,
            auth_info=auth_info,
            profile_slug=effective_slug,
            profile_db_id=profile_db_id,
            app_slug=app_slug,
        )

    # 5. Convert to tool defs
    tool_defs = har_entries_to_tool_defs(annotated, auth_info, session_name=session_name)

    # 6. Generate operation module sources
    op_sources: dict[str, str] = {}
    for td in tool_defs:
        source = generate_operation_module(td, auth_plan)
        op_sources[td["name"]] = source

    # 7. Generate server.py
    server_source = generate_server(tool_defs, effective_slug, session_name)

    # Determine server_id
    server_id = f"{app_slug}-{session_id[:8]}"
    app_name = _app_name_from_slug(app_slug)

    # Collect file list for manifest
    output_files: list[str] = ["server.py", "tools.json", "noui_runtime/auth.py"]
    if auth_plan:
        output_files.append("auth_plan.json")
    for name in op_sources:
        output_files.append(f"operations/{name}.py")

    # 8. Write files
    out_path = Path(output_dir)
    out_path.mkdir(parents=True, exist_ok=True)

    (out_path / "server.py").write_text(server_source, encoding="utf-8")
    (out_path / "tools.json").write_text(
        json.dumps(tool_defs, indent=2, default=str), encoding="utf-8"
    )

    ops_dir = out_path / "operations"
    ops_dir.mkdir(exist_ok=True)
    (ops_dir / "__init__.py").write_text("", encoding="utf-8")
    for name, source in op_sources.items():
        (ops_dir / f"{name}.py").write_text(source, encoding="utf-8")

    # noui_runtime/auth.py
    from backend.config import settings as _settings
    runtime_dir = out_path / "noui_runtime"
    runtime_dir.mkdir(exist_ok=True)
    (runtime_dir / "__init__.py").write_text("", encoding="utf-8")
    auth_source = _auth_adapter_mod.generate_auth_adapter(_settings.tabby_api_host)
    (runtime_dir / "auth.py").write_text(auth_source, encoding="utf-8")

    # 9. auth_plan.json (only when auth is required)
    if auth_plan:
        (out_path / "auth_plan.json").write_text(
            json.dumps(auth_plan, indent=2), encoding="utf-8"
        )

    # 10. manifest.json
    manifest = generate_manifest(
        server_id=server_id,
        app_name=app_name,
        app_slug=app_slug,
        workflow_session_id=session_id,
        workflow_name=session_name,
        tabby_profile_id=tabby_profile_id,
        tool_defs=tool_defs,
        output_files=output_files,
        profile_slug=effective_slug,
        profile_db_id=profile_db_id,
        auth_strategy=auth_plan.get("strategy", ""),
    )
    (out_path / "manifest.json").write_text(
        json.dumps(manifest, indent=2), encoding="utf-8"
    )

    return manifest
