"""Expedia Stay Search — FastMCP server (generalized, CDP-based)

Searches for hotels on Expedia with real pricing, ratings, and reviews.
Uses Chrome DevTools Protocol to execute requests from inside an
authenticated Tabby browser session, bypassing Akamai bot detection.

Generated by NoUI v2 — generalized with /noui-generalize (CDP workaround).
"""

from __future__ import annotations

from mcp.server.fastmcp import FastMCP
from operations import search_hotels as _op_search_hotels

mcp = FastMCP("Expedia Stay Search")


@mcp.tool()
async def search_hotels(
    destination: str,
    check_in: str,
    check_out: str,
    guests: int = 2,
    rooms: int = 1,
) -> dict:
    """Search for available hotels on Expedia by destination and dates.

    Returns up to 25 hotel listings with per-night price, total price,
    guest rating (out of 10), review count, refund policy, and a direct
    booking URL on Expedia.

    Requires a running Tabby browser session with an active Expedia page
    on CDP port 9222.

    Args:
        destination: City or place name (e.g. "Miami Beach" or "Paris, France")
        check_in: Check-in date in YYYY-MM-DD format
        check_out: Check-out date in YYYY-MM-DD format
        guests: Number of adult guests (default: 2)
        rooms: Number of rooms (default: 1)
    """
    return await _op_search_hotels.execute(
        destination=destination,
        check_in=check_in,
        check_out=check_out,
        guests=guests,
        rooms=rooms,
    )


if __name__ == "__main__":
    mcp.run()
